[project]
name = "ai-bug-fixer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
]
